<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HAWB</name>
   <tag></tag>
   <elementGuidId>5770cae5-b3b9-4981-8a13-61bdc3aff4ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cell-1-undefined']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cell-1-undefined > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6238b70-255b-45f3-9c13-2e548e672d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tag</name>
      <type>Main</type>
      <value>allowRowEvents</value>
      <webElementGuid>9c4620e5-8d01-46a3-acab-c87b15f05654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SF1011864459155</value>
      <webElementGuid>cc2a3271-588d-40d5-8efa-a26511f315b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row-0&quot;)/div[@id=&quot;cell-1-undefined&quot;]/div[1]</value>
      <webElementGuid>7ba06a73-35c5-4963-b1be-9bec6b325cb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cell-1-undefined']/div</value>
      <webElementGuid>ce0d5207-fcf4-4d4e-a5cc-f57dc3bdcc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TYPE'])[1]/following::div[4]</value>
      <webElementGuid>e2f48f90-228f-4949-90b6-3f2a60f87a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UPLOADED DATE'])[1]/following::div[7]</value>
      <webElementGuid>cfedab12-e73c-451b-b371-ce8d764c1065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Y'])[1]/preceding::div[1]</value>
      <webElementGuid>0564464a-24cf-4c2f-bf9a-706d54f8658a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UPLOAD'])[1]/preceding::div[15]</value>
      <webElementGuid>37b406f9-4f47-4843-a709-cdc2224bdde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SF1011864459155']/parent::*</value>
      <webElementGuid>60507c3b-eb38-4fe1-95a5-0e6257b46705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/div/div</value>
      <webElementGuid>b06e8b01-f404-4cc4-b8b1-1447f5aae712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'SF1011864459155' or . = 'SF1011864459155')]</value>
      <webElementGuid>bb850509-a5ee-415e-875d-7c50a267f3c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
