<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//div[@id='cell-6-undefined']</description>
   <name>div_StatusDateCells</name>
   <tag></tag>
   <elementGuidId>28d833b5-baa0-4de4-97e7-5a0e65255658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cell-6-undefined']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
