<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TYPE</name>
   <tag></tag>
   <elementGuidId>0cf20b97-c698-428e-8253-88e83e8df1d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/section/div/div[2]/div/div[2]/div[2]/div/div/div/div/div[9]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20623c65-5f6f-40b5-8cf0-3099b2b2bee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-column-id</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>941935a2-42d3-40da-aef5-1f1586f3931c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-eDVOW ftzeFU</value>
      <webElementGuid>c7dc0adc-820d-4ee1-83c3-aabcd897f329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TYPE</value>
      <webElementGuid>9f6504e6-0d63-40f7-8078-aa4f426d73b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/section[@class=&quot;h-screen overflow-auto&quot;]/div[@class=&quot;min-h-screen&quot;]/div[@class=&quot;flex xl:justify-center lg:justify-between justify-center items-start g-6&quot;]/div[@class=&quot;grow-0 shrink-1 md:shrink-0 basis-auto h-full xl:w-full lg:w-full md:w-12/12 mb-12 md:mb-0&quot;]/div[@class=&quot;xl:w-12/12 lg:w-12/12 md:w-12/12 mb-12 md:mb-10 px-10 bg-white rounded-xl&quot;]/div[@class=&quot;sc-dmcuvF jrjCcS bg-white overflow-y-scroll&quot;]/div[@class=&quot;sc-fLcmKr cXjMVu&quot;]/div[@class=&quot;sc-bcXGCL hkPEcy rdt_Table&quot;]/div[@class=&quot;sc-gswONk kUPsJI rdt_TableHead&quot;]/div[@class=&quot;sc-dkrGBB iUKfll rdt_TableHeadRow&quot;]/div[@class=&quot;sc-hLBatu sc-eDvShL sc-ipEzrc gIHijI cPssfJ eVQERa rdt_TableCol&quot;]/div[@class=&quot;sc-csuRvn ilhcix rdt_TableCol_Sortable&quot;]/div[@class=&quot;sc-eDVOW ftzeFU&quot;]</value>
      <webElementGuid>d2c7746a-0836-4d21-9563-8d582d2cd846</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/section/div/div[2]/div/div[2]/div[2]/div/div/div/div/div[9]/div/div</value>
      <webElementGuid>896ea247-4c17-4f6b-99ca-4e98cab9b826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UPLOADED DATE'])[1]/following::div[3]</value>
      <webElementGuid>2d6b75f3-0958-4a6d-9baa-038650f3c5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SF TRANSMISSION DATE'])[1]/following::div[6]</value>
      <webElementGuid>995a1504-79e4-4fec-a5cb-162f81a11fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E1004'])[1]/preceding::div[3]</value>
      <webElementGuid>8639df87-740c-4ade-917e-d25f711697f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UPLOAD-NMM_User'])[1]/preceding::div[17]</value>
      <webElementGuid>9c1e34d6-6d2e-4ba4-86d6-ba26cc499ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TYPE']/parent::*</value>
      <webElementGuid>32614c15-442f-42bf-9a18-d457b3e98fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div</value>
      <webElementGuid>826871bf-da31-4870-b14e-94624e05c0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TYPE' or . = 'TYPE')]</value>
      <webElementGuid>ae42355d-4ebe-4be6-8e3a-8e382bb7c49d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
