<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HAWB</name>
   <tag></tag>
   <elementGuidId>ff223e86-efc1-4629-a7e0-fc72eccbda02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'HAWB']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;HAWB&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;HAWB&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09401bad-28e9-49be-b6c0-94d86d5a2150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>HAWB</value>
      <webElementGuid>b0698d30-1dae-4ac9-970a-ccbf469a47f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-span-12 h-[1.65rem] border-2 border-blue-900 rounded w-auto text-sm px-2</value>
      <webElementGuid>4b6c5630-347e-4802-a50a-a4241b8db624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8037ba43-b4e8-4c4c-953a-0500fd7406fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>HAWB</value>
      <webElementGuid>59251dc3-b9ab-4b1e-bcbd-5a49d9219538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b317048e9c4b93a665de427741d6c4d0</value>
      <webElementGuid>ed321809-2ceb-4011-ac08-83adaa419ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'HAWB']</value>
      <webElementGuid>3c3fa251-774e-42f6-8a88-d933522c9c8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'HAWB']</value>
      <webElementGuid>9b6d0acf-3063-4fb6-83be-67660f539279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'HAWB' and @type = 'text' and @placeholder = 'HAWB']</value>
      <webElementGuid>787a577d-35ac-4643-b1c4-2cbad13fa50c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
